SCHEMACHECK=	check-jsonschema --check-metaschema

check:
	$(SCHEMACHECK) at_stop.yaml
	$(SCHEMACHECK) journey.yaml
	$(SCHEMACHECK) last_stop.yaml
	$(SCHEMACHECK) latest_ticket.yaml
	$(SCHEMACHECK) next_stop.yaml
	$(SCHEMACHECK) status.yaml
	$(SCHEMACHECK) vehicle.yaml
	$(SCHEMACHECK) remaining_stops.yaml
	$(SCHEMACHECK) run_monitoring.yaml
